version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: aas_db
      POSTGRES_USER: aas_user
      POSTGRES_PASSWORD: secure_password123
    volumes:
      - aas_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  web:
    build: .
    command: gunicorn aas.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 90 --threads 2
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # These are still needed to tell Django where the DB is,
      # and are loaded into the container's environment before env_file takes precedence for shared names
      - DATABASE_NAME=aas_db
      - DATABASE_USER=aas_user
      - DATABASE_PASSWORD=secure_password123
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    env_file:
      - .env  # <--- This line tells Docker Compose to load variables from .env
    restart: always

volumes:
  aas_pgdata:
  pgadmin_data: